export const MentalAbilities = [
  "Road Dog",
  "Field General",
  "Headstrong",
  "Fan Favorite",
  "Clearheaded",
  "Winning Time",
  "The Natural",
  "Best Friend",
  "OL Rally",
  "DL Rally",
  "Legion",
  "Clutch Kicker",
] as const;

export const PhysicalAbilities = [
  "Off Platform",
  "Pull Down",
  "On Time",
  "Sleight of Hand",
  "Mobile Deadeye",
  "Downhill",
  "Extender",
  "Option King",
  "Dot!",
  "Mobile Resistance",
  "Resistance",
  "Step Up",
  "Shifty",
  "Side Step",
  "Workhorse",
  "360",
  "Safety Valve",
  "Takeoff",
  "Recoup",
  "Battering Ram",
  "Ball Security",
  "Balanced",
  "Arm Bar",
  "Headfirst",
  "Sidekick",
  "Strong Grip",
  "Second Level",
  "Pocket Shield",
  "Screen Enforcer",
  "50/50",
  "Cutter",
  "Double Dip",
  "Press Pro",
  "Sure Hands",
  "Lay Out",
  "Quick Drop",
  "Outside Shield",
  "Wear Down",
  "PA Shield",
  "Inside Shield",
  "Ground N Pound",
  "Option Shield",
  "Quick Step",
  "Grip Breaker",
  "Inside Disruptor",
  "Outside Disruptor",
  "Option Disruptor",
  "Pocket Disruptor",
  "Hammer",
  "Quick Jump",
  "Duress",
  "Take Down",
  "Knockout",
  "House Call",
  "Robber",
  "Bouncer",
  "Wrap Up",
  "Blow Up",
  "Aftershock",
  "Jammer",
  "Blanket Coverage",
  "Ballhawk",
  "Chip Shot",
  "Deep Range",
  "Mega Leg",
  "Coffin Corner",
] as const;

export type MentalAbility = (typeof MentalAbilities)[number];
export type PhysicalAbility = (typeof PhysicalAbilities)[number];

/** A mental/physical ability a player has earned, at a tier from 1 to 4. */
export type PlayerMentalAbility = { name: MentalAbility; level: number };
export type PlayerPhysicalAbility = { name: PhysicalAbility; level: number };
